  # Mark Shust's Docker Configuration for Magento (https://github.com/markshust/docker-magento)
# Version 23.2.3

version: "3"

services:
  app:
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - ./shared-files/ssl-cert:/var/www/ssl-cert
      - ./shared-files/logs/nginx:/var/log/nginx
      - ./src:/var/www/html
      - sockdata:/sock


  phpfpm:
    build: ./docker/php
    links:
      - db
    volumes: *appvolumes

  db:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    env_file: docker/mysql/db.env
    volumes:
      - ./shared-files/logs/mysql:/var/log/mysql
      - ./shared-files/database:/var/lib/mysql
      - ./shared-files/dump/:/tmp/dump

volumes:
  #appdata:
  #dbdata:
  sockdata: